### ISSUE TITLE
Input Needed: Variable Code Clunkiness

### ISSUE THREAD

**Issue by fwilson-603** [uoft-lgcu/uoft-lgcu.github.io#15]
I've sorted out how to get pages to generate peoples' names based on an external file. Problem is: including a link to the dept. website and metatext for that link, combined with a if/else statement to account for the fact that some people are not listed by their preferred names on the website... the code gets really clunky.

> {% if site.data.members.president1.fullname %}[{{site.data.members.president1.name}}](https://www.linguistics.utoronto.ca/people/directories/graduate-students/{{site.data.members.president1.fullname | slugify}} "Department directory entry for {{site.data.members.president1.name}}"){% else %}[{{site.data.members.president1}}](https://www.linguistics.utoronto.ca/people/directories/graduate-students/{{site.data.members.president1 | slugify}} "Department directory entry for {{site.data.members.president1}}"){% endif %}

Is needed to generate a single name with a link. (You can see it functioning in the index.md file right now) This works fine (and the reference file _data/members.yml is way cleaner), but it makes the markdown really difficult to read.

Are we willing to consider this an acceptable solution? If not, any ideas on how to fix it? Possibly we could use javascript to store the long naming code in another file, and call it via a shorter function anytime we actually want to name someone in-text, but I'm a little lost on how to get javascript and liquid to interface that way.

**Comment by laurest** [comment]
Would we be able to just have a "name" and "fullname" field for everyone? With the understanding that "fullname" is whatever is on the Department website and "name" is whatever they should be listed as here.

**Comment by laurest** [comment]
It might even be possible to have one of the two name fields default to being equal to the other? e.g. have name: Fiona Wilson, fullname: name. Not sure if that sort of thing is allowed though.

**Comment by fwilson-603** [comment]
Having two name fields for everyone would be possible; I was trying to avoid that because it basically doubles the work required to update things. I doubt there's a perfect solution to the problem, it's more of a conceptual issue of where we want to put the complexity (e.g. in the markdown, in the update file, etc.) I'm not sure if one of the name fields can call the other. I'll give it a try.

**Comment by fwilson-603** [comment]
Update: it does not appear possible to call one of the name fields with the other.

**Comment by laurest** [comment]
Dang. Personally I would prefer having all the names in the update file formatted the same way - if I were the one maintaining this. Which I probably won't be. idk.

**Comment by fwilson-603** [comment]
I decided to accept redundancy in the interest of maintaining clarity. So now every entry has a "name" and a "fullname" (usually the same), but the markdown stays simpler. Thanks for the input!
