### ISSUE TITLE
Are we sticking with the uoft-lgcu.github.io URL?

### ISSUE THREAD

**Issue by laurest** [uoft-lgcu/uoft-lgcu.github.io#17]
Should we/I get the ulife/dept website/etc links updated now - or were we going to look at getting a different URL for the new website, and should we/I wait to send the new url to those places?

**Comment by fwilson-603** [comment]
I think the hold-up is that we would need LGCU approval in order to license the new URL, and we haven't had a meeting where we could do that. Option 1) ask for a special vote to be sent round approving the URL expense, or 2) update the links as-is and deal with the URL at some point in the future.

**Comment by laurest** [comment]
Either option seems fine with me. The current URL is still pretty compact, so it would be fine to stick with it for now I think. I don't know how common/reasonable special votes are, but if that would be quick, getting it out of the way would also be good.
