### ISSUE TITLE
LGCU Book Collection public link concerns

### ISSUE THREAD

**Issue by rcraioveanu** [uoft-lgcu/uoft-lgcu.github.io#19]
I'm vaguely concerned that having the Library catalogue be an openly editable spreadsheet is still sliiightly risky. It's nice that only the first column can be edited, but internet trolls do exist, and if anyone on the internet can anonymously erase our record of who has what book that seems non-ideal.

**Comment by fwilson-603** [comment]
Update: have emailed the library committee to ask about getting a link to a read-only version of the library catalogue spreadsheet. When they reply, we can change the link to that, and possibly include a note to email the contact person for the editable link.

**Comment by fwilson-603** [comment]
Update: Link should now go to a read-only version, and text on the webpage has been altered to suit that.
